### ISSUE TITLE
Usage - best practices & ?

### ISSUE THREAD

**Issue by kjhosein** [jwplayer/logstash-tools#2]
Hello @alertedsnake - thanks for writing this script. It looks promising to me, but I'm a bit puzzled about its usage. My apologies as I'm not a Pythonista.

1. does it pull back *all* of the files in the bucket each time, and attempt to send onto Redis/stdout?
2. did you envision that one would run this every _x_ # of minutes (so as to keep your Logstash data up to date)? That's how I'm guessing at any rate, but then it wouldn't seem to fit if the 1st ques is true.

Thanks!

**Comment by alertedsnake** [comment]
Do you mean the CloudTrail script?  It pulls all files for the specified day from the S3 bucket, and imports them into Logstash via Redis.  I run this once a day.

The other script is for tailing a logfile and streaming it directly into Logstash via Redis.

**Comment by kjhosein** [comment]
Sorry! Yes, I did mean the cloudtrail-importer.

Ah, ok that makes sense. Would you consider tweaking it so that it could be run more frequently while keeping track of which logs it has already ingested?

**Comment by alertedsnake** [comment]
Feel free to fork it and do that, I don't have a need for such a feature.
